[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "featuregraph-core"
version = "0.1.0"
description = "FeatureGraph Developer Toolkit"
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
authors = [
    { name = "Nazia Habib" },
]
dependencies = [
    "pandas>=1.5",
    "numpy>=1.23",
    "matplotlib>=3.5",
    "requests>=2.25",
]

[tool.setuptools.packages.find]
where = ["src"]
